version: '2.2'
networks:
  internal:
    driver: bridge
  external:
    driver: bridge
services:
  app:
    build: .
    networks:
      internal:
        aliases:
          - app
  proxy:
    restart: on-failure
    image: nginx:alpine
    volumes: ['./.nginx/default.conf:/etc/nginx/conf.d/default.conf']
    ports: ['80:80']
    networks:
      internal:
        aliases: []
      external:
        aliases: []
    healthcheck:
      test: wget --quiet --tries=1 --spider http://127.0.0.1:80/ || exit 1
      timeout: 1s
      retries: 99
    depends_on: 
      - app
